name: wings_model
description: wings_model
version: 0.1.2
author: chuanci<chuanci@vip.qq.com>
homepage: https://github.com/chuanci/wings_model

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build_runner: ^1.10.0
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
dev_dependencies: